#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 135
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  sym_raw_string_literal = 1,
  anon_sym_DQUOTE = 2,
  aux_sym_interpreted_string_literal_token1 = 3,
  sym_escape_sequence = 4,
  sym__identifier = 5,
  anon_sym_module = 6,
  anon_sym_LPAREN = 7,
  anon_sym_LF = 8,
  anon_sym_RPAREN = 9,
  anon_sym_go = 10,
  anon_sym_toolchain = 11,
  anon_sym_require = 12,
  anon_sym_exclude = 13,
  anon_sym_replace = 14,
  anon_sym_EQ_GT = 15,
  anon_sym_retract = 16,
  anon_sym_LBRACK = 17,
  anon_sym_COMMA = 18,
  anon_sym_RBRACK = 19,
  sym_comment = 20,
  sym_source_file = 21,
  sym__directive = 22,
  sym__string_literal = 23,
  sym_interpreted_string_literal = 24,
  sym__string_or_ident = 25,
  sym_module_path = 26,
  sym_go_version = 27,
  sym_version = 28,
  sym_module_directive = 29,
  sym_go_directive = 30,
  sym_toolchain_directive = 31,
  sym_toolchain_name = 32,
  sym_require_directive = 33,
  sym_require_spec = 34,
  sym_exclude_directive = 35,
  sym_exclude_spec = 36,
  sym_replace_directive = 37,
  sym_replace_spec = 38,
  sym_file_path = 39,
  sym_retract_directive = 40,
  sym_retract_spec = 41,
  aux_sym_source_file_repeat1 = 42,
  aux_sym_interpreted_string_literal_repeat1 = 43,
  aux_sym_require_directive_repeat1 = 44,
  aux_sym_exclude_directive_repeat1 = 45,
  aux_sym_replace_directive_repeat1 = 46,
  aux_sym_retract_directive_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_raw_string_literal] = "raw_string_literal",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_interpreted_string_literal_token1] = "interpreted_string_literal_token1",
  [sym_escape_sequence] = "escape_sequence",
  [sym__identifier] = "_identifier",
  [anon_sym_module] = "module",
  [anon_sym_LPAREN] = "(",
  [anon_sym_LF] = "\n",
  [anon_sym_RPAREN] = ")",
  [anon_sym_go] = "go",
  [anon_sym_toolchain] = "toolchain",
  [anon_sym_require] = "require",
  [anon_sym_exclude] = "exclude",
  [anon_sym_replace] = "replace",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_retract] = "retract",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__directive] = "_directive",
  [sym__string_literal] = "_string_literal",
  [sym_interpreted_string_literal] = "interpreted_string_literal",
  [sym__string_or_ident] = "_string_or_ident",
  [sym_module_path] = "module_path",
  [sym_go_version] = "go_version",
  [sym_version] = "version",
  [sym_module_directive] = "module_directive",
  [sym_go_directive] = "go_directive",
  [sym_toolchain_directive] = "toolchain_directive",
  [sym_toolchain_name] = "toolchain_name",
  [sym_require_directive] = "require_directive",
  [sym_require_spec] = "require_spec",
  [sym_exclude_directive] = "exclude_directive",
  [sym_exclude_spec] = "exclude_spec",
  [sym_replace_directive] = "replace_directive",
  [sym_replace_spec] = "replace_spec",
  [sym_file_path] = "file_path",
  [sym_retract_directive] = "retract_directive",
  [sym_retract_spec] = "retract_spec",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_interpreted_string_literal_repeat1] = "interpreted_string_literal_repeat1",
  [aux_sym_require_directive_repeat1] = "require_directive_repeat1",
  [aux_sym_exclude_directive_repeat1] = "exclude_directive_repeat1",
  [aux_sym_replace_directive_repeat1] = "replace_directive_repeat1",
  [aux_sym_retract_directive_repeat1] = "retract_directive_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_raw_string_literal] = sym_raw_string_literal,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_interpreted_string_literal_token1] = aux_sym_interpreted_string_literal_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym__identifier] = sym__identifier,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_go] = anon_sym_go,
  [anon_sym_toolchain] = anon_sym_toolchain,
  [anon_sym_require] = anon_sym_require,
  [anon_sym_exclude] = anon_sym_exclude,
  [anon_sym_replace] = anon_sym_replace,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_retract] = anon_sym_retract,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__directive] = sym__directive,
  [sym__string_literal] = sym__string_literal,
  [sym_interpreted_string_literal] = sym_interpreted_string_literal,
  [sym__string_or_ident] = sym__string_or_ident,
  [sym_module_path] = sym_module_path,
  [sym_go_version] = sym_go_version,
  [sym_version] = sym_version,
  [sym_module_directive] = sym_module_directive,
  [sym_go_directive] = sym_go_directive,
  [sym_toolchain_directive] = sym_toolchain_directive,
  [sym_toolchain_name] = sym_toolchain_name,
  [sym_require_directive] = sym_require_directive,
  [sym_require_spec] = sym_require_spec,
  [sym_exclude_directive] = sym_exclude_directive,
  [sym_exclude_spec] = sym_exclude_spec,
  [sym_replace_directive] = sym_replace_directive,
  [sym_replace_spec] = sym_replace_spec,
  [sym_file_path] = sym_file_path,
  [sym_retract_directive] = sym_retract_directive,
  [sym_retract_spec] = sym_retract_spec,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_interpreted_string_literal_repeat1] = aux_sym_interpreted_string_literal_repeat1,
  [aux_sym_require_directive_repeat1] = aux_sym_require_directive_repeat1,
  [aux_sym_exclude_directive_repeat1] = aux_sym_exclude_directive_repeat1,
  [aux_sym_replace_directive_repeat1] = aux_sym_replace_directive_repeat1,
  [aux_sym_retract_directive_repeat1] = aux_sym_retract_directive_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_interpreted_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym__identifier] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_go] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_toolchain] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_require] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exclude] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_replace] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_retract] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__directive] = {
    .visible = false,
    .named = true,
  },
  [sym__string_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_interpreted_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__string_or_ident] = {
    .visible = false,
    .named = true,
  },
  [sym_module_path] = {
    .visible = true,
    .named = true,
  },
  [sym_go_version] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [sym_module_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_go_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_toolchain_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_toolchain_name] = {
    .visible = true,
    .named = true,
  },
  [sym_require_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_require_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_exclude_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_exclude_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_replace_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_replace_spec] = {
    .visible = true,
    .named = true,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [sym_retract_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_retract_spec] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpreted_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_require_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_exclude_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_replace_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_retract_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 29,
  [52] = 35,
  [53] = 24,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 55,
  [61] = 61,
  [62] = 62,
  [63] = 54,
  [64] = 62,
  [65] = 56,
  [66] = 66,
  [67] = 57,
  [68] = 59,
  [69] = 30,
  [70] = 50,
  [71] = 34,
  [72] = 72,
  [73] = 73,
  [74] = 33,
  [75] = 75,
  [76] = 47,
  [77] = 49,
  [78] = 28,
  [79] = 4,
  [80] = 6,
  [81] = 72,
  [82] = 75,
  [83] = 72,
  [84] = 75,
  [85] = 72,
  [86] = 75,
  [87] = 87,
  [88] = 41,
  [89] = 6,
  [90] = 28,
  [91] = 91,
  [92] = 4,
  [93] = 93,
  [94] = 4,
  [95] = 95,
  [96] = 6,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 91,
  [104] = 104,
  [105] = 105,
  [106] = 28,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 99,
  [116] = 116,
  [117] = 113,
  [118] = 118,
  [119] = 119,
  [120] = 110,
  [121] = 121,
  [122] = 114,
  [123] = 123,
  [124] = 112,
  [125] = 116,
  [126] = 126,
  [127] = 127,
  [128] = 109,
  [129] = 129,
  [130] = 111,
  [131] = 131,
  [132] = 119,
  [133] = 133,
  [134] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(56);
      ADVANCE_MAP(
        '"', 59,
        '(', 73,
        ')', 76,
        ',', 87,
        '/', 9,
        '=', 10,
        '[', 86,
        '\\', 11,
        ']', 88,
        '`', 12,
        'e', 46,
        'g', 35,
        'm', 36,
        'r', 22,
        't', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(55);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(4);
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead == '\\') ADVANCE(11);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(75);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '`') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(75);
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(59);
      if (lookahead == '/') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '(') ADVANCE(74);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == '`') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == ')') ADVANCE(77);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '[') ADVANCE(86);
      if (lookahead == '`') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '=') ADVANCE(68);
      if (lookahead == '`') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '/') ADVANCE(67);
      if (lookahead == '`') ADVANCE(69);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(89);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(83);
      END_STATE();
    case 11:
      if (lookahead == 'U') ADVANCE(54);
      if (lookahead == 'u') ADVANCE(50);
      if (lookahead == 'x') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 12:
      if (lookahead == '`') ADVANCE(57);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 18:
      if (lookahead == 'c') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'd') ADVANCE(45);
      END_STATE();
    case 21:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(80);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(79);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(78);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(30);
      if (lookahead == 'q') ADVANCE(43);
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(85);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(21);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 46:
      if (lookahead == 'x') ADVANCE(16);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 55:
      if (eof) ADVANCE(56);
      ADVANCE_MAP(
        '"', 59,
        '(', 73,
        ')', 76,
        ',', 87,
        '/', 9,
        '=', 10,
        '[', 86,
        ']', 88,
        '`', 12,
        'e', 46,
        'g', 35,
        'm', 36,
        'r', 22,
        't', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_raw_string_literal);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_raw_string_literal);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_interpreted_string_literal_token1);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_interpreted_string_literal_token1);
      if (lookahead == '/') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_interpreted_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '/') ADVANCE(70);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '>') ADVANCE(84);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '`') ADVANCE(58);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ',' ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(12);
      if (lookahead != 0) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == ',' ||
          lookahead == '[' ||
          lookahead == ']') ADVANCE(89);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__identifier);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_go);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_toolchain);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_require);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_exclude);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_replace);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(71);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_retract);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(89);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 8},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 8},
  [68] = {.lex_state = 8},
  [69] = {.lex_state = 6},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 6},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 6},
  [77] = {.lex_state = 6},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 6},
  [89] = {.lex_state = 8},
  [90] = {.lex_state = 8},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 8},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 3},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 3},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 3},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 3},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 3},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 3},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 3},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 3},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 3},
  [134] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_raw_string_literal] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_go] = ACTIONS(1),
    [anon_sym_toolchain] = ACTIONS(1),
    [anon_sym_require] = ACTIONS(1),
    [anon_sym_exclude] = ACTIONS(1),
    [anon_sym_replace] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_retract] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(93),
    [sym__directive] = STATE(2),
    [sym_module_directive] = STATE(2),
    [sym_go_directive] = STATE(2),
    [sym_toolchain_directive] = STATE(2),
    [sym_require_directive] = STATE(2),
    [sym_exclude_directive] = STATE(2),
    [sym_replace_directive] = STATE(2),
    [sym_retract_directive] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_module] = ACTIONS(7),
    [anon_sym_go] = ACTIONS(9),
    [anon_sym_toolchain] = ACTIONS(11),
    [anon_sym_require] = ACTIONS(13),
    [anon_sym_exclude] = ACTIONS(15),
    [anon_sym_replace] = ACTIONS(17),
    [anon_sym_retract] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_module,
    ACTIONS(9), 1,
      anon_sym_go,
    ACTIONS(11), 1,
      anon_sym_toolchain,
    ACTIONS(13), 1,
      anon_sym_require,
    ACTIONS(15), 1,
      anon_sym_exclude,
    ACTIONS(17), 1,
      anon_sym_replace,
    ACTIONS(19), 1,
      anon_sym_retract,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(3), 9,
      sym__directive,
      sym_module_directive,
      sym_go_directive,
      sym_toolchain_directive,
      sym_require_directive,
      sym_exclude_directive,
      sym_replace_directive,
      sym_retract_directive,
      aux_sym_source_file_repeat1,
  [39] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      anon_sym_module,
    ACTIONS(28), 1,
      anon_sym_go,
    ACTIONS(31), 1,
      anon_sym_toolchain,
    ACTIONS(34), 1,
      anon_sym_require,
    ACTIONS(37), 1,
      anon_sym_exclude,
    ACTIONS(40), 1,
      anon_sym_replace,
    ACTIONS(43), 1,
      anon_sym_retract,
    STATE(3), 9,
      sym__directive,
      sym_module_directive,
      sym_go_directive,
      sym_toolchain_directive,
      sym_require_directive,
      sym_exclude_directive,
      sym_replace_directive,
      sym_retract_directive,
      aux_sym_source_file_repeat1,
  [78] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 11,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_EQ_GT,
      anon_sym_retract,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [95] = 8,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(52), 1,
      anon_sym_RPAREN,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      sym_comment,
    STATE(110), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(7), 2,
      sym_retract_spec,
      aux_sym_retract_directive_repeat1,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [124] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 11,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_EQ_GT,
      anon_sym_retract,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [141] = 8,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(60), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(8), 2,
      sym_retract_spec,
      aux_sym_retract_directive_repeat1,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [170] = 8,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    STATE(110), 1,
      sym_version,
    ACTIONS(62), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(8), 2,
      sym_retract_spec,
      aux_sym_retract_directive_repeat1,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [199] = 8,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_LBRACK,
    STATE(26), 1,
      sym_retract_spec,
    STATE(120), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [227] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_DQUOTE,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_module_path,
    ACTIONS(77), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(10), 2,
      sym_replace_spec,
      aux_sym_replace_directive_repeat1,
    STATE(78), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [253] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_module_path,
    ACTIONS(85), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(17), 2,
      sym_require_spec,
      aux_sym_require_directive_repeat1,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [279] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(91), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_module_path,
    ACTIONS(85), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(11), 2,
      sym_require_spec,
      aux_sym_require_directive_repeat1,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [305] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_module_path,
    ACTIONS(85), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(15), 2,
      sym_exclude_spec,
      aux_sym_exclude_directive_repeat1,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [331] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_module_path,
    ACTIONS(95), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(16), 2,
      sym_replace_spec,
      aux_sym_replace_directive_repeat1,
    STATE(78), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [357] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_module_path,
    ACTIONS(85), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(18), 2,
      sym_exclude_spec,
      aux_sym_exclude_directive_repeat1,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [383] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(103), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_module_path,
    ACTIONS(95), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(10), 2,
      sym_replace_spec,
      aux_sym_replace_directive_repeat1,
    STATE(78), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [409] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_DQUOTE,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(65), 1,
      sym_module_path,
    ACTIONS(105), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(17), 2,
      sym_require_spec,
      aux_sym_require_directive_repeat1,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [435] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(64), 1,
      sym_module_path,
    ACTIONS(113), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(18), 2,
      sym_exclude_spec,
      aux_sym_exclude_directive_repeat1,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [461] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_DQUOTE,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    STATE(24), 1,
      sym_module_path,
    STATE(25), 1,
      sym_replace_spec,
    ACTIONS(95), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(78), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [486] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(123), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_exclude_spec,
    STATE(62), 1,
      sym_module_path,
    ACTIONS(85), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [511] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(125), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym_require_spec,
    STATE(56), 1,
      sym_module_path,
    ACTIONS(85), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [550] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [564] = 6,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(135), 1,
      anon_sym_EQ_GT,
    STATE(111), 1,
      sym_version,
    ACTIONS(131), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(91), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [642] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_raw_string_literal,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym__identifier,
    STATE(57), 1,
      sym_module_path,
    STATE(122), 1,
      sym_file_path,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [666] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [680] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [708] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [736] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_raw_string_literal,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym__identifier,
    STATE(63), 1,
      sym_module_path,
    STATE(99), 1,
      sym_file_path,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [760] = 6,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(159), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_module_path,
    ACTIONS(157), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(28), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [782] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(161), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [796] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [810] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [824] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [838] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [852] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [866] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(173), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [880] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [894] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [908] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [922] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [936] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [950] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [964] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 8,
      ts_builtin_sym_end,
      anon_sym_module,
      anon_sym_go,
      anon_sym_toolchain,
      anon_sym_require,
      anon_sym_exclude,
      anon_sym_replace,
      anon_sym_retract,
  [978] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_raw_string_literal,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym__identifier,
    STATE(67), 1,
      sym_module_path,
    STATE(114), 1,
      sym_file_path,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1002] = 7,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(85), 1,
      sym_raw_string_literal,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(145), 1,
      sym__identifier,
    STATE(54), 1,
      sym_module_path,
    STATE(115), 1,
      sym_file_path,
    STATE(90), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1026] = 6,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    ACTIONS(189), 1,
      anon_sym_EQ_GT,
    STATE(130), 1,
      sym_version,
    ACTIONS(131), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(91), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1048] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(116), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1067] = 5,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    STATE(132), 1,
      sym_version,
    ACTIONS(131), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(91), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1086] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(124), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1105] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(99), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1124] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(104), 1,
      sym_module_path,
    ACTIONS(191), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(106), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1143] = 5,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    STATE(109), 1,
      sym_version,
    ACTIONS(131), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(91), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1162] = 5,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    STATE(119), 1,
      sym_version,
    ACTIONS(131), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(91), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1181] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(118), 1,
      sym_go_version,
    ACTIONS(193), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(100), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1200] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(108), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1219] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(125), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1238] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(134), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1257] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(112), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1276] = 5,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    STATE(32), 1,
      sym_toolchain_name,
    ACTIONS(195), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(31), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1295] = 5,
    ACTIONS(50), 1,
      anon_sym_DQUOTE,
    ACTIONS(56), 1,
      sym_comment,
    STATE(115), 1,
      sym_version,
    ACTIONS(48), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(103), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1314] = 5,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    STATE(128), 1,
      sym_version,
    ACTIONS(131), 2,
      sym_raw_string_literal,
      sym__identifier,
    STATE(91), 3,
      sym__string_literal,
      sym_interpreted_string_literal,
      sym__string_or_ident,
  [1333] = 3,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    ACTIONS(197), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1346] = 3,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_LBRACK,
    ACTIONS(199), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1359] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(201), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1369] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    STATE(75), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(205), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1383] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(209), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1397] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(212), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1407] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(216), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1421] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(218), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1431] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(220), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1441] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(222), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_EQ_GT,
  [1451] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(224), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_EQ_GT,
  [1461] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(226), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_EQ_GT,
  [1471] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_DQUOTE,
    STATE(82), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(230), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1485] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(216), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1499] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DQUOTE,
    STATE(84), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(236), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1513] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(216), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1527] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_DQUOTE,
    STATE(86), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(242), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1541] = 4,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      aux_sym_interpreted_string_literal_repeat1,
    ACTIONS(216), 2,
      aux_sym_interpreted_string_literal_token1,
      sym_escape_sequence,
  [1555] = 3,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LF,
    ACTIONS(246), 3,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
  [1567] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(250), 4,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
      anon_sym_RPAREN,
  [1577] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(226), 3,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
  [1586] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(222), 3,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
  [1595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 3,
      anon_sym_EQ_GT,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1604] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(224), 3,
      sym_raw_string_literal,
      anon_sym_DQUOTE,
      sym__identifier,
  [1613] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      ts_builtin_sym_end,
  [1620] = 2,
    ACTIONS(46), 1,
      anon_sym_LF,
    ACTIONS(56), 1,
      sym_comment,
  [1627] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LF,
  [1634] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_LF,
  [1641] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(258), 1,
      anon_sym_LF,
  [1648] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_LF,
  [1655] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_LF,
  [1662] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(264), 1,
      anon_sym_LF,
  [1669] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_LF,
  [1676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
  [1683] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LF,
  [1690] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_LF,
  [1697] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LF,
  [1704] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_LF,
  [1711] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(274), 1,
      anon_sym_LF,
  [1718] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_LF,
  [1725] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_RBRACK,
  [1732] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_LF,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      anon_sym_EQ_GT,
  [1746] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_LF,
  [1753] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_LF,
  [1760] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_LF,
  [1767] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_LF,
  [1774] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_LF,
  [1781] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_LF,
  [1788] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_LF,
  [1795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_COMMA,
  [1802] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_LF,
  [1809] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(302), 1,
      anon_sym_LF,
  [1816] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_LF,
  [1823] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_LF,
  [1830] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_LF,
  [1837] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_LF,
  [1844] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_LF,
  [1851] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(314), 1,
      anon_sym_LF,
  [1858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_RBRACK,
  [1865] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_LF,
  [1872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      anon_sym_EQ_GT,
  [1879] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_LF,
  [1886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      anon_sym_COMMA,
  [1893] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_LF,
  [1900] = 2,
    ACTIONS(56), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 95,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 141,
  [SMALL_STATE(8)] = 170,
  [SMALL_STATE(9)] = 199,
  [SMALL_STATE(10)] = 227,
  [SMALL_STATE(11)] = 253,
  [SMALL_STATE(12)] = 279,
  [SMALL_STATE(13)] = 305,
  [SMALL_STATE(14)] = 331,
  [SMALL_STATE(15)] = 357,
  [SMALL_STATE(16)] = 383,
  [SMALL_STATE(17)] = 409,
  [SMALL_STATE(18)] = 435,
  [SMALL_STATE(19)] = 461,
  [SMALL_STATE(20)] = 486,
  [SMALL_STATE(21)] = 511,
  [SMALL_STATE(22)] = 536,
  [SMALL_STATE(23)] = 550,
  [SMALL_STATE(24)] = 564,
  [SMALL_STATE(25)] = 586,
  [SMALL_STATE(26)] = 600,
  [SMALL_STATE(27)] = 614,
  [SMALL_STATE(28)] = 628,
  [SMALL_STATE(29)] = 642,
  [SMALL_STATE(30)] = 666,
  [SMALL_STATE(31)] = 680,
  [SMALL_STATE(32)] = 694,
  [SMALL_STATE(33)] = 708,
  [SMALL_STATE(34)] = 722,
  [SMALL_STATE(35)] = 736,
  [SMALL_STATE(36)] = 760,
  [SMALL_STATE(37)] = 782,
  [SMALL_STATE(38)] = 796,
  [SMALL_STATE(39)] = 810,
  [SMALL_STATE(40)] = 824,
  [SMALL_STATE(41)] = 838,
  [SMALL_STATE(42)] = 852,
  [SMALL_STATE(43)] = 866,
  [SMALL_STATE(44)] = 880,
  [SMALL_STATE(45)] = 894,
  [SMALL_STATE(46)] = 908,
  [SMALL_STATE(47)] = 922,
  [SMALL_STATE(48)] = 936,
  [SMALL_STATE(49)] = 950,
  [SMALL_STATE(50)] = 964,
  [SMALL_STATE(51)] = 978,
  [SMALL_STATE(52)] = 1002,
  [SMALL_STATE(53)] = 1026,
  [SMALL_STATE(54)] = 1048,
  [SMALL_STATE(55)] = 1067,
  [SMALL_STATE(56)] = 1086,
  [SMALL_STATE(57)] = 1105,
  [SMALL_STATE(58)] = 1124,
  [SMALL_STATE(59)] = 1143,
  [SMALL_STATE(60)] = 1162,
  [SMALL_STATE(61)] = 1181,
  [SMALL_STATE(62)] = 1200,
  [SMALL_STATE(63)] = 1219,
  [SMALL_STATE(64)] = 1238,
  [SMALL_STATE(65)] = 1257,
  [SMALL_STATE(66)] = 1276,
  [SMALL_STATE(67)] = 1295,
  [SMALL_STATE(68)] = 1314,
  [SMALL_STATE(69)] = 1333,
  [SMALL_STATE(70)] = 1346,
  [SMALL_STATE(71)] = 1359,
  [SMALL_STATE(72)] = 1369,
  [SMALL_STATE(73)] = 1383,
  [SMALL_STATE(74)] = 1397,
  [SMALL_STATE(75)] = 1407,
  [SMALL_STATE(76)] = 1421,
  [SMALL_STATE(77)] = 1431,
  [SMALL_STATE(78)] = 1441,
  [SMALL_STATE(79)] = 1451,
  [SMALL_STATE(80)] = 1461,
  [SMALL_STATE(81)] = 1471,
  [SMALL_STATE(82)] = 1485,
  [SMALL_STATE(83)] = 1499,
  [SMALL_STATE(84)] = 1513,
  [SMALL_STATE(85)] = 1527,
  [SMALL_STATE(86)] = 1541,
  [SMALL_STATE(87)] = 1555,
  [SMALL_STATE(88)] = 1567,
  [SMALL_STATE(89)] = 1577,
  [SMALL_STATE(90)] = 1586,
  [SMALL_STATE(91)] = 1595,
  [SMALL_STATE(92)] = 1604,
  [SMALL_STATE(93)] = 1613,
  [SMALL_STATE(94)] = 1620,
  [SMALL_STATE(95)] = 1627,
  [SMALL_STATE(96)] = 1634,
  [SMALL_STATE(97)] = 1641,
  [SMALL_STATE(98)] = 1648,
  [SMALL_STATE(99)] = 1655,
  [SMALL_STATE(100)] = 1662,
  [SMALL_STATE(101)] = 1669,
  [SMALL_STATE(102)] = 1676,
  [SMALL_STATE(103)] = 1683,
  [SMALL_STATE(104)] = 1690,
  [SMALL_STATE(105)] = 1697,
  [SMALL_STATE(106)] = 1704,
  [SMALL_STATE(107)] = 1711,
  [SMALL_STATE(108)] = 1718,
  [SMALL_STATE(109)] = 1725,
  [SMALL_STATE(110)] = 1732,
  [SMALL_STATE(111)] = 1739,
  [SMALL_STATE(112)] = 1746,
  [SMALL_STATE(113)] = 1753,
  [SMALL_STATE(114)] = 1760,
  [SMALL_STATE(115)] = 1767,
  [SMALL_STATE(116)] = 1774,
  [SMALL_STATE(117)] = 1781,
  [SMALL_STATE(118)] = 1788,
  [SMALL_STATE(119)] = 1795,
  [SMALL_STATE(120)] = 1802,
  [SMALL_STATE(121)] = 1809,
  [SMALL_STATE(122)] = 1816,
  [SMALL_STATE(123)] = 1823,
  [SMALL_STATE(124)] = 1830,
  [SMALL_STATE(125)] = 1837,
  [SMALL_STATE(126)] = 1844,
  [SMALL_STATE(127)] = 1851,
  [SMALL_STATE(128)] = 1858,
  [SMALL_STATE(129)] = 1865,
  [SMALL_STATE(130)] = 1872,
  [SMALL_STATE(131)] = 1879,
  [SMALL_STATE(132)] = 1886,
  [SMALL_STATE(133)] = 1893,
  [SMALL_STATE(134)] = 1900,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpreted_string_literal, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpreted_string_literal, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_retract_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_retract_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_retract_directive_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_retract_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_replace_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_replace_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_replace_directive_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_require_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_require_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_require_directive_repeat1, 2, 0, 0),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_exclude_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_exclude_directive_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_exclude_directive_repeat1, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(121),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_directive, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exclude_directive, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replace_directive, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_retract_directive, 2, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_directive, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_path, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_retract_spec, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toolchain_name, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_toolchain_directive, 2, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_spec, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exclude_spec, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_directive, 5, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_directive, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exclude_directive, 5, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replace_directive, 5, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replace_spec, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_retract_directive, 5, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_directive, 6, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_require_directive, 6, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_exclude_directive, 6, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replace_directive, 6, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replace_spec, 5, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_retract_directive, 6, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_replace_spec, 6, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_retract_spec, 6, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [193] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_retract_spec, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_retract_spec, 6, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_exclude_spec, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpreted_string_literal_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interpreted_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_require_spec, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replace_spec, 5, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replace_spec, 6, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_module_path, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpreted_string_literal, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpreted_string_literal, 3, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [234] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__string_or_ident, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_path, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_replace_spec, 4, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_version, 1, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_go_version, 1, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gomod(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
